### ISSUE TITLE
Problema con CORS!!!! --Ranking--

### ISSUE THREAD

**Issue by santiihoyos** [santiihoyos/GitKraken_minigame#1]
Hola,

He implementado la conexión a servidor del ranking mediante un web-service el problema que me he encontrado es que por politicas de seguridad de JavaScript no puedo hacer peticiones http desde un servidor a otro, para ello tendría que implementar algo llamado **CORS** os dejo la documentacion en unity donde advierten del tema ¿alguien sabe por dónde tirar?

> http://docs.unity3d.com/Manual/webgl-networking.html

De todas formas el ranking si que funciona como se puede ver en este enlace:

> http://51.254.134.174/prueba/

pero funciona porque el webservice y el juego están en el mismo servidor.

Un saludo!

**Comment by karlossius** [comment]
Yo lo siento pero de eso no tengo ni idea, aunque creo que había más opciones/plugins para conectarse a la red. Consultaré con antiguos compañeros.
De todas formas, si el ranking va mientras el juego y el webservice estén alojados en el mismo sitio, ¿qué problema hay?

**Comment by santiihoyos** [comment]
Pues el problema viene que la web donde va estar alojado el juego es un espacio que proporciona GitHub(http://santiihoyos.github.io/GitKraken_minigame/) que habíamos dicho en principio de usar ese pero si se sube ahí la petición que tendría que hacer el juego es fuera de su dominio y salta lo de CORS.

@jakala ¿sabes algo al respecto?

**Comment by karlossius** [comment]
¿No podríamos probar a subirlo en Google Drive?

**Comment by santiihoyos** [comment]
¿Google Drive proporciona un servidor web con php?, ese es el principal problema que hay con el espacio web que nos da github que nos proporciona alojamiento pero no hay servidor para ejecutar código del lado servidor(php) .

Ayer estuve probando con las clases de red de .NEt de C# pero en WebGL no son validas, luego probe con WWW de UnityEngine pero no funcionaba y por último he probado la nueva api para redes de Unity UnityWebRequest del paquete UnityEngine que es la que funciona. Así que de momento se puede tirar del servidor que he pasado antes o si alguno sabe como arreglar lo del CORS mejor.

**Comment by jakala** [comment]
Buenas,

el problema del cross origin suele ser porque el servidor donde esta 
alojado el servicio que quieres usar tiene activado la proteccion del 
cross origin. quizas este sea el caso y se pueda desactivar.

Puedes probar en el directorio /prueba de tu servidor (donde tienes el 
index.html) a poner un archivo .htaccess con el contenido:

Header set Access-Control-Allow-Origin "*"

A ver si con eso resulta

Un saludo,

Jakala del pantano

**Comment by karlossius** [comment]
Me dicen que existe un paquete llamado PhotonNetwork para juego online. No sé si te servirá para el ranking, pero si permite multijugador online, algo ayudará...

**Comment by santiihoyos** [comment]
@jakala  He probado lo de .htaccess pero nada incluso he probado a añadir la cabecera homologa de esa en PHP en el servicio pero nada.

@karlossius  Voy a echarle un ojo a lo de Phothon que tiene buena pinta.

**Comment by jakala** [comment]
@santiihoyos has probado a poner el .htaccess en la página del github? En lugar del servidor....

**Comment by santiihoyos** [comment]
Tema solucionado usaremos un dominio .tk gratuito por 12 meses con posibilidad de renovarlo redirigido al server que hospeda el juego con lo que nos olvidamos de CORS (aunque se intentara saber como hacerlo funcionar más adelante con tiempo).

**Comment by jakala** [comment]
Respecto a este tema:

La web que está alojada en github incrusta ahora los archivos remotos del build que hay en el tercer de santii. Esto da como resultado un control mayor desde la web para el tema de los tamaños.

Sin embargo me da un problema de cors, el cual según he leído se resuelve añadiendo la cabecera de content-type en la respuesta del servidor.

@santi,puedes pasarme el script del webservice que utilizas para el halloffame?

Sugerencia: que tal el nombre de "hall of kraken" para esa pantalla? 😸

**Comment by karlossius** [comment]
Mñeh, puede valer

**Comment by N2AGames** [comment]
Me vale :D
