### ISSUE TITLE
Fallos en la web

### ISSUE THREAD

**Issue by N2AGames** [santiihoyos/GitKraken_minigame#10]
Chicos no va la web ni el hall of fame D:

**Comment by JesusRodriguezDeveloper** [comment]
Se nos habia caido el VPS porque ha detectado el ataque ddos de Angel jaja
Ya esta online

2016-04-12 17:26 GMT+02:00 Not2Awesome Games notifications@github.com:

**Comment by santiihoyos** [comment]
@jakala ¿qué ha podido pasar? habrá sido por la chorrada de antes del Apache Benchmark ? 

-Se había bloqueado el Firewall no caído.

**Comment by jakala** [comment]
El benchmark afecta al servidor web del dominio .tk, no afectaría a la web que está en tu alojamiento de github. El problema es que no sabemos cuánto soporta el .tk (recordad que es un iframe que contiene a github.) es posible que con pocas conexiones concurrentes les reviente el servidor.

Siento decir que la solución puede pasar x cambiar de dominio... O esperar al viernes rezando.😸

A mi me ha dado desde la tablet con chrome un error de array overflow... A cuanta memoria está compilada la última build?

**Comment by N2AGames** [comment]
512mb

**Comment by jakala** [comment]
Otra cosa que podíamos hacer es cambiar la redirección del dominio, para que redirija al alojamiento de github.  Así el que soportaría todas las conexiones sería github (es más probable que lo soporte debido al servicio que ofrecen).

Lo malo es que aparecería en el navegador el alojamiento github... Lo bueno que el tweet seria valido (ademas de que funcionaría el botón maximizar 😸)

**Comment by N2AGames** [comment]
Esa opción me parece correcta, y la mejor de momento. Gracias por la
investigación Ángel :D

**Comment by jakala** [comment]
Una cosa: acabo de ver la app y los comentarios. Hay uno muy importante, y es que la app no tiene un botón salir... De momento se puede salir con las opciones de la tablet cerrando la app pero estaría bien poner dicho boton...

Ahora le doy 4 estrellas 😸

**Comment by JesusRodriguezDeveloper** [comment]
Mañana lo agregamos, que hay que mejorar cosillas. Hay uno con 150 rt....

**Comment by N2AGames** [comment]
El del comentario es mi hermano XD Me lo ha dicho según la ha probado el
cabron hahahaha

**Comment by N2AGames** [comment]
RT de axosoft :D

**Comment by santiihoyos** [comment]
Esto esta jodido, vamos terceros jaja

@jakala  pues entonces ni idea que habrá pasado con el server.

**Comment by santiihoyos** [comment]
Solucionado!
