### ISSUE TITLE
Audio DJ casi acabado

### ISSUE THREAD

**Issue by N2AGames** [santiihoyos/GitKraken_minigame#2]
Hola chicos,
el DJ de cambio de canción esta casi acabado, me gustaría encontrar otros audios que esten hechos de diferente manera, es decir, si yo intento hacer transición entre lo que tenemos, no va a quedar bien bien nunca ya que no tienen el mismo bitrate y no estan los ritmos acompasados. La idea es coger dos o mas audios que al superponerles unos sobre otros, queden bien y se pueda ir "escalando" en la complegidad del resultado, para asi poder darla mas rtimo a la canción a medida que avanza la dificultad.

Esa es la idea, el problema es que es dificil encontrar audios con cc-by o cc-zero de estas características, yo he buscado un rato y he desistido sin encontrar resultados.

Visto que esto esta hecho, y no queda mal con lo que tengo, me pongo con el diseño de la interfaz, que tiene su tela tambien :smile:

**Comment by santiihoyos** [comment]
Pues en principio se podría dejar así si dices que no queda muy mal porque nos quedamos sin tiempo tiene que salir este finde a más tardar el lunes debe estar ya publicado para que nos dé tiempo a compartirlo y que la gente lo juegue.

**Comment by N2AGames** [comment]
Oko entonces me pongo con la interfaz. Necesitamos un diseño decente para la interfaz, lo puedo intentar yo pero igual sale un truño XD

**Comment by N2AGames** [comment]
Ahi van los audios de GameOver y Project Cancel, el que mas os mole le meteis pls :smile: 
[LoseGameAudios.zip](https://github.com/santiihoyos/GitKraken_minigame/files/210711/LoseGameAudios.zip)

**Comment by santiihoyos** [comment]
Audios OK
Tema cerrado!
