### ISSUE TITLE
Nombre del juego

### ISSUE THREAD

**Issue by santiihoyos** [santiihoyos/GitKraken_minigame#3]
Hola de nuevo,

Estoy mirando para crear un dominio .tk en plan= gitkrakengame.tk para que redirija al servidor donde esta el juego asi nos quitamos las limitaciones del espacio que nos da github y queda mejor el nombre y mas facil.

necesito que pensemos ya un nombre, a mi me gusta:

> Master Tentacles (Tentáculos maestros)

o

> Kraken's Tentacles

@jakala @N2AGames @JesusRodriguezDeveloper @karlossius

**Comment by karlossius** [comment]
Y "Feed the Kraken!"?

**Comment by N2AGames** [comment]
No está mal...

**Comment by santiihoyos** [comment]
@karlossius  no está mal.

¿más ideas?

**Comment by JesusRodriguezDeveloper** [comment]
me gusta  "Feed the Kraken!"
Survivor Kraken, Manager Kraken... como veais

**Comment by santiihoyos** [comment]
Krakenbius, nueva propuesta de nombre de @JesusRodriguezDeveloper en plan:

De los jugadores de polybius... no recomendado para embarazadas... KRAKENBIUS!!!!

**Comment by N2AGames** [comment]
Krakenmaster?

**Comment by karlossius** [comment]
Krakenmaster no me mola...
Krakenbius, si tiene algo que ver, aunque solo sea la estética, con el otro, vale, aunque puede inducir a pensar que es de los mismos, y no es así.
Por mí Feed the Kraken! o Krakenbius (preferentemente el primero).

**Comment by N2AGames** [comment]
Feed the kraken!! El mejor

**Comment by santiihoyos** [comment]
Pues nos quedamos con Feed The Kraken!.

**Comment by JesusRodriguezDeveloper** [comment]
Yo decia Krakenbius por el parecido visual con polybius y porque alimentar
no tiene mucho sentido si lo estamos orientando a que el juego es un
proyecto (cancelled project, etc). Y ya que lo hacemos friki los que
conozcan polybius se darán cuenta de la referencia / homenaje.

**Comment by karlossius** [comment]
Y "Kontrol the Kraken!"?
Yo lo de "Feed" era por un juego de palabras con "Free/Release the Kraken". Krakenbius no me suena mal del todo, pero quizá sí un poco forzado, nada más.

**Comment by JesusRodriguezDeveloper** [comment]
Kontrol de kraken no está mal. De todas formas cualquiera de los tres me
gusta, así que como decidáis.

**Comment by santiihoyos** [comment]
Pues decidid ahora que luego ya no se podrá cambiar... y hay que pillar el dominio y hacer todas las redirecciones si no decis nada nos quedamos con "Feed The Kraken".

> Yo "Feed The Kraken" o "Krankenbius".

**Comment by N2AGames** [comment]
Feed the kraken loko

**Comment by santiihoyos** [comment]
Ok, pues zanjamos el tema, se queda como está.

:ok:
