### ISSUE TITLE
Tematica de la web:

### ISSUE THREAD

**Issue by santiihoyos** [santiihoyos/GitKraken_minigame#6]
Segun parece el jeugo lo queiren para cuando se active el programa les lleve a una pagina comoe esta:

> https://www.gitkraken.com/activation-success

tienen ahí un minijuego, deberíamos ambientar la nuestra con los mismos colores.

**Comment by karlossius** [comment]
Yo los veo ya bastante parecidos, pero estoy de acuerdo en cambiar los tonos para que sean los mismos o casi. No tengo problema.

**Comment by jakala** [comment]
Buenas,

os adjunto una imagen con una captura de pantalla de la web como esta 
actualmente. El boton maximizar no me funciona si esta dentro del 
dominio .tk. (por lo del iframe que contiene la web). Estoy con ello.

Ya tenemos botones de facebook, google y twitter.

**Comment by santiihoyos** [comment]
Web perfecta!

Tema cerrado.
