### ISSUE TITLE
Compilación en Unity 5.4

### ISSUE THREAD

**Issue by santiihoyos** [santiihoyos/GitKraken_minigame#7]
Hola,

Estaba leyendo por la API cosas.. y me he encontrado que la clase UnityWebRequest ya está fuera del paquete experimental y está ahora en Unityengine.Networking. En la 5.3 que es la que estamos usando todos nosotros, está en: UnityEngine.Experimental.Networking ... 

El tema está en que la clase la han mejorado por algún crash que sufría(y que me da a mi a ratos)...

Propongo compilar el juego si no hay ningún otro inconveniente en la versión 5.4 de Unity y usar las mejoras.

PD: la versión 5.4 no es estable aún.

Un saludo!

**Comment by karlossius** [comment]
El lunes actualizo y que Dios nos asista :P

**Comment by santiihoyos** [comment]
Nos quedamos en 5.3.4f1
